# Generated by Django 2.2 on 2019-06-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fields_startups_and_tags_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'Can view unpublished post'),), 'verbose_name': 'blog post'},
        ),
    ]
